baseURL = "/"
defaultContentLanguage = "ru"
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap"]
languageCode = "ru"
sectionPagesMenu = "main"
title = "@atipugin"

[menu]
  [[menu.footer]]
  name = "GitHub"
  url = "https://github.com/atipugin"

  [[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/atipugin"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]

[author]
email = "atipugin@gmail.com"
name = "Alexander Tipugin"

[params]
description = "Здесь будет описание"
