baseURL = "/"
defaultContentLanguage = "ru"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
languageCode = "ru"
sectionPagesMenu = "main"
title = "@atipugin"

[menu]
  [[menu.footer]]
  name = "GitHub"
  url = "https://github.com/atipugin"

  [[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/atipugin"

  [[menu.footer]]
  name = "RSS"
  url = "/index.xml"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]

[author]
email = "atipugin@gmail.com"
name = "Alexander Tipugin"
image = "images/me.png"

[params]
description = "Здесь будет описание"
